name: Build UABEA Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish UABEANext4.Desktop/UABEANext4.Desktop.csproj --configuration Release --no-build --output ./publish

    - name: Remove unused platforms
      run: find ./publish/runtimes/* -maxdepth 0 ! -name linux-x64 -type d -exec rm -rf {} + 2>/dev/null || true
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: uabea-ubuntu
        path: ./publish