name: Build UABEA Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Publish main application
      run: dotnet publish UABEANext4.Desktop/UABEANext4.Desktop.csproj --configuration Release --no-build --output ./publish --runtime win-x64 --self-contained false

    - name: Copy native libraries
      run: |
        New-Item -Path "./publish/runtimes/win-x64/native" -ItemType Directory -Force
        Copy-Item -Path "NativeLibs/win-x64/*" -Destination "./publish/runtimes/win-x64/native/" -Recurse
      shell: pwsh

    - name: Copy plugins and dependencies
      run: |
        # Ensure plugins directory exists
        New-Item -Path "./publish/plugins" -ItemType Directory -Force
        
        # Copy all plugin DLLs
        Copy-Item -Path "AudioPlugin/bin/Release/net8.0/AudioPlugin.dll" -Destination "./publish/plugins/"
        Copy-Item -Path "FontPlugin/bin/Release/net8.0/FontPlugin.dll" -Destination "./publish/plugins/"
        Copy-Item -Path "MeshPlugin/bin/Release/net8.0/MeshPlugin.dll" -Destination "./publish/plugins/"
        Copy-Item -Path "TextAssetPlugin/bin/Release/net8.0/TextAssetPlugin.dll" -Destination "./publish/plugins/"
        Copy-Item -Path "TexturePlugin/bin/Release/net8.0/TexturePlugin.dll" -Destination "./publish/plugins/"
        
        # Copy plugin dependencies from Libs folder
        Copy-Item -Path "Libs/AssetsTools.NET.Texture.dll" -Destination "./publish/plugins/"
        
        # Copy audio plugin dependencies if they exist
        if (Test-Path "AudioPlugin/bin/Release/net8.0/Fmod5Sharp.dll") {
          Copy-Item -Path "AudioPlugin/bin/Release/net8.0/Fmod5Sharp.dll" -Destination "./publish/plugins/"
        }
        if (Test-Path "AudioPlugin/bin/Release/net8.0/NAudio.Core.dll") {
          Copy-Item -Path "AudioPlugin/bin/Release/net8.0/NAudio.Core.dll" -Destination "./publish/plugins/"
        }
        if (Test-Path "AudioPlugin/bin/Release/net8.0/OggVorbisEncoder.dll") {
          Copy-Item -Path "AudioPlugin/bin/Release/net8.0/OggVorbisEncoder.dll" -Destination "./publish/plugins/"
        }
        
        # Copy ReleaseFiles
        Copy-Item -Path "ReleaseFiles/*" -Destination "./publish/" -Recurse
      shell: pwsh
    
    - name: Remove unused platforms
      run: |
        if (Test-Path "./publish/runtimes") {
          Get-ChildItem -Path "./publish/runtimes" -Directory | Where-Object { $_.Name -notin @("win-x64", "win7-x64", "win") } | Remove-Item -Recurse -Force
        }
      shell: pwsh
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: uabea-windows
        path: ./publish