name: Build UABEA Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish UABEANext4.Desktop/UABEANext4.Desktop.csproj --configuration Release --no-build --output ./publish
    
    - name: Remove unused platforms
      run: |
        if (Test-Path "./publish/runtimes") {
          Get-ChildItem -Path "./publish/runtimes" -Directory | Where-Object { $_.Name -notin @("win-x64", "win7-x64", "win") } | Remove-Item -Recurse -Force
        }
      shell: pwsh
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: uabea-windows
        path: ./publish